name: CI/CD

on:
  push:
    branches:
      - main 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: npm test -- --coverage

   
